#!/bin/bash
MAIN_SESSION="main"

tmux new-session -d -s $MAIN_SESSION

#admin
tmux new-window -t $MAIN_SESSION:0 -k -n admin

#synergy
SESSION="synergy"
SESSION_NAME="synergy"
tmux new-session -d -s $SESSION
tmux new-window -t "$SESSION:0" -k -n svn
tmux send-keys -t "$SESSION:0" "cd ~/workspace/synergy" C-m
tmux send-keys -t "$SESSION:0" "clear" C-m
tmux new-window -t "$SESSION:1" -n portal-root
tmux send-keys -t "$SESSION:1" "cd ~/workspace/synergy/synergy/src/main/portal-root" C-m
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux send-keys -t "$SESSION:1" "vim ../webapp/WEB-INF/wro.groovy"
tmux new-window -t "$SESSION:2" -n crowler
tmux send-keys -t "$SESSION:2" "cd ~/workspace/synergy/synergy/src/main/portal-root" C-m
tmux send-keys -t "$SESSION:2" "clear" C-m
tmux new-window -t "$SESSION:3" -n struts
tmux send-keys -t "$SESSION:3" "cd ~/workspace/synergy/synergy/src/main/resources/template/synergy" C-m
tmux send-keys -t "$SESSION:3" "clear" C-m
tmux new-window -t "$SESSION:4" -n server
tmux send-keys -t "$SESSION:4" "cd ~/" C-m
tmux send-keys -t "$SESSION:4" "clear" C-m
tmux send-keys -t "$SESSION:4" "./synergy-build.sh; ./synergy-start.sh"
tmux new-window -t "$SESSION:5" -n rest-test
tmux send-keys -t "$SESSION:5" "cd ~/workspace/synergy/integration/synergy-rs-impl/src/test/java/com/roche/xp2/rest" C-m
tmux send-keys -t "$SESSION:5" "clear" C-m

tmux new-window -t $MAIN_SESSION:1 -n "$SESSION_NAME"
tmux send-keys -t $MAIN_SESSION:1 "unset TMUX; tmux attach -t $SESSION" C-m

#synergy
SESSION="synergy_2_13"
SESSION_NAME="synergy-2.13"
tmux new-session -d -s $SESSION
tmux new-window -t "$SESSION:0" -k -n svn
tmux send-keys -t "$SESSION:0" "cd ~/workspace/synergy-2.13" C-m
tmux send-keys -t "$SESSION:0" "clear" C-m
tmux new-window -t "$SESSION:1" -n portal-root
tmux send-keys -t "$SESSION:1" "cd ~/workspace/synergy-2.13/synergy/src/main/portal-root" C-m
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux send-keys -t "$SESSION:1" "vim ../webapp/WEB-INF/wro.groovy"
tmux new-window -t "$SESSION:2" -n crowler
tmux send-keys -t "$SESSION:2" "cd ~/workspace/synergy-2.13/synergy/src/main/portal-root" C-m
tmux send-keys -t "$SESSION:2" "clear" C-m
tmux new-window -t "$SESSION:3" -n struts
tmux send-keys -t "$SESSION:3" "cd ~/workspace/synergy-2.13/synergy/src/main/resources/template/synergy" C-m
tmux send-keys -t "$SESSION:3" "clear" C-m
tmux new-window -t "$SESSION:4" -k -n server
tmux send-keys -t "$SESSION:4" "cd ~/workspace/synergy-2.13" C-m
tmux send-keys -t "$SESSION:4" "clear" C-m

tmux new-window -t $MAIN_SESSION:2 -n "$SESSION_NAME"
tmux send-keys -t $MAIN_SESSION:2 "unset TMUX; tmux attach -t $SESSION" C-m

#syngular
SESSION="syngular"
SESSION_NAME="syngular"
tmux new-session -d -s $SESSION
tmux new-window -t "$SESSION:0" -k -n git
tmux send-keys -t "$SESSION:0" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:0" "clear" C-m
tmux new-window -t "$SESSION:1" -n vim
tmux send-keys -t "$SESSION:1" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux new-window -t "$SESSION:2" -n yeoman
tmux send-keys -t "$SESSION:2" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:2" "clear" C-m
tmux new-window -t "$SESSION:3" -n server
tmux send-keys -t "$SESSION:3" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:3" "clear" C-m
tmux send-keys -t "$SESSION:3" "grunt server" C-m
tmux new-window -t "$SESSION:4" -n testacular
tmux send-keys -t "$SESSION:4" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:4" "clear" C-m
tmux send-keys -t "$SESSION:4" "testacular start testacular.conf.js" C-m
tmux new-window -t "$SESSION:5" -n crowler
tmux send-keys -t "$SESSION:5" "cd ~/workspace/syngular" C-m
tmux send-keys -t "$SESSION:5" "clear" C-m

tmux new-window -t $MAIN_SESSION:3 -n "$SESSION_NAME"
tmux send-keys -t $MAIN_SESSION:3 "unset TMUX; tmux attach -t $SESSION" C-m

#syngular
SESSION="new_syngular"
SESSION_NAME="new-syngular"
tmux new-session -d -s $SESSION
tmux new-window -t "$SESSION:0" -k -n git
tmux send-keys -t "$SESSION:0" "cd ~/workspace/new-syngular" C-m
tmux send-keys -t "$SESSION:0" "clear" C-m
tmux new-window -t "$SESSION:1" -n vim
tmux send-keys -t "$SESSION:1" "cd ~/workspace/new-syngular" C-m
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux new-window -t "$SESSION:2" -n crawler
tmux send-keys -t "$SESSION:2" "cd ~/workspace/new-syngular" C-m
tmux send-keys -t "$SESSION:2" "clear" C-m
tmux new-window -t "$SESSION:3" -n crawler
tmux send-keys -t "$SESSION:3" "cd ~/workspace/new-syngular" C-m
tmux send-keys -t "$SESSION:3" "clear" C-m

tmux new-window -t $MAIN_SESSION:4 -n "$SESSION_NAME"
tmux send-keys -t $MAIN_SESSION:4 "unset TMUX; tmux attach -t $SESSION" C-m

#syngular
SESSION="generator_angular"
SESSION_NAME="generator-angular"
tmux new-session -d -s $SESSION
tmux new-window -t "$SESSION:0" -k -n git
tmux send-keys -t "$SESSION:0" "cd ~/workspace/generator-angular" C-m
tmux send-keys -t "$SESSION:0" "clear" C-m
tmux new-window -t "$SESSION:1" -n vim
tmux send-keys -t "$SESSION:1" "cd ~/workspace/generator-angular" C-m
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux new-window -t "$SESSION:2" -n crawler
tmux send-keys -t "$SESSION:2" "cd ~/workspace/generator-angular" C-m
tmux send-keys -t "$SESSION:2" "clear" C-m
tmux new-window -t "$SESSION:3" -n crawler
tmux send-keys -t "$SESSION:3" "cd ~/workspace/generator-angular" C-m
tmux send-keys -t "$SESSION:3" "clear" C-m

tmux new-window -t $MAIN_SESSION:5 -n "$SESSION_NAME"
tmux send-keys -t $MAIN_SESSION:5 "unset TMUX; tmux attach -t $SESSION" C-m

#attach
tmux attach -t $MAIN_SESSION
